# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'untitled.ui'
# Created by: PyQt5 UI code generator 5.15.4
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.backends.backend_qt5agg import FigureCanvas
from matplotlib.backends.qt_compat import QtWidgets, QtCore, QtGui
from matplotlib.figure import Figure
import analyze_screen
from fonts import *


class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(1116, 970)
        self.centralwidget = QtWidgets.QWidget()
        self.setCentralWidget(self.centralwidget)

        self.matplotlib_frame = QtWidgets.QWidget(self.centralwidget)
        self.matplotlib_frame.setGeometry(QtCore.QRect(450, 30, 640, 400))

        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, self.matplotlib_frame)
        self.matplotlib_layout = QtWidgets.QVBoxLayout(self.matplotlib_frame)
        self.matplotlib_layout.addWidget(self.toolbar)
        self.matplotlib_layout.addWidget(self.canvas)

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 381, 371))
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)

        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(40, 858, 512, 40))
        self.startButton.setFont(buttonFont)
        self.startButton.setAutoDefault(False)

        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setGeometry(QtCore.QRect(555, 858, 512, 40))
        self.stopButton.setFont(buttonFont)
        self.stopButton.setAutoDefault(False)

        self.analyzeButton = QtWidgets.QPushButton(self.centralwidget)
        self.analyzeButton.setGeometry(QtCore.QRect(40, 900, 1030, 40))
        self.analyzeButton.setFont(buttonFont)
        self.analyzeButton.setAutoDefault(False)
        self.analyzeButton.clicked.connect(self.openAnalyzeScreen)

        self.logSection = QtWidgets.QTextBrowser(self.centralwidget)
        self.logSection.setGeometry(QtCore.QRect(40, 685, 1030, 160))

        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setFont(spinFont)
        self.spinBox.setRange(0, 9999)
        self.gridLayout.addWidget(self.spinBox, 1, 0, 1, 1)

        self.time1Button = QtWidgets.QPushButton(self.layoutWidget)
        self.time1Button.setFont(buttonFont)
        self.time1Button.setAutoDefault(False)
        self.time1Button.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.time1Button, 1, 1, 1, 1)

        self.time2Label = QtWidgets.QLabel(self.layoutWidget)
        self.time2Label.setFont(labelFont)
        self.gridLayout.addWidget(self.time2Label, 2, 0, 1, 2)

        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setFont(spinFont)
        self.spinBox_2.setRange(0, 9999)
        self.gridLayout.addWidget(self.spinBox_2, 3, 0, 1, 1)

        self.time1Label = QtWidgets.QLabel(self.layoutWidget)
        self.time1Label.setFont(labelFont)
        self.gridLayout.addWidget(self.time1Label, 0, 0, 1, 2)

        self.time2Button = QtWidgets.QPushButton(self.layoutWidget)
        self.time2Button.setFont(buttonFont)
        self.time2Button.setAutoDefault(False)
        self.gridLayout.addWidget(self.time2Button, 3, 1, 1, 1)

        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setFont(spinFont)
        self.spinBox_3.setRange(0, 9999)
        self.gridLayout.addWidget(self.spinBox_3, 5, 0, 1, 1)

        self.time3Button = QtWidgets.QPushButton(self.layoutWidget)
        self.time3Button.setFont(buttonFont)
        self.time3Button.setAutoDefault(False)
        self.gridLayout.addWidget(self.time3Button, 5, 1, 1, 1)

        self.time3Label = QtWidgets.QLabel(self.layoutWidget)
        self.time3Label.setFont(labelFont)
        self.gridLayout.addWidget(self.time3Label, 4, 0, 1, 2)

        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(980, 610, 100, 50))
        self.exportButton.setFont(buttonFont)
        self.exportButton.setAutoDefault(False)

        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(980, 555, 100, 50))
        self.clearButton.setFont(buttonFont)
        self.clearButton.setAutoDefault(False)

        self.textEditFolder = QtWidgets.QTextEdit(self.centralwidget)  # csv path
        self.textEditFolder.setGeometry(QtCore.QRect(40, 500, 920, 50))

        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(980, 500, 100, 50))
        self.browseButton.setFont(buttonFont)
        self.browseButton.setAutoDefault(False)

        self.folderPathLabel = QtWidgets.QLabel(self.centralwidget)
        self.folderPathLabel.setGeometry(QtCore.QRect(40, 470, 120, 20))
        self.folderPathLabel.setFont(labelFont)

        self.levelLabel = QtWidgets.QLabel(self.centralwidget)
        self.levelLabel.setGeometry(QtCore.QRect(40, 580, 120, 20))
        self.levelLabel.setFont(labelFont)

        self.repeatLabel = QtWidgets.QLabel(self.centralwidget)
        self.repeatLabel.setGeometry(QtCore.QRect(460, 580, 120, 20))
        self.repeatLabel.setFont(labelFont)

        self.textEditSath = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSath.setGeometry(QtCore.QRect(40, 610, 400, 50))
        self.textEditSath.setFont(textEditFont)

        self.textEditTekrar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditTekrar.setGeometry(QtCore.QRect(460, 610, 500, 50))
        self.textEditTekrar.setFont(textEditFont)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def openAnalyzeScreen(self):
        self.analyzeScreen = analyze_screen.AnalyzeApp()
        self.analyzeScreen.show()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate

        self.setWindowTitle(_translate("MainWindow", "Electronic Nose"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.time1Button.setText(_translate("MainWindow", "Single run"))
        self.time2Button.setText(_translate("MainWindow", "Single run"))
        self.time3Button.setText(_translate("MainWindow", "Single run"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.time2Label.setText(_translate("MainWindow", "Time 2"))
        self.time1Label.setText(_translate("MainWindow", "Time 1"))
        self.time3Label.setText(_translate("MainWindow", "Time 3"))
        self.folderPathLabel.setText(_translate("MainWindow", "Folder Path:"))
        self.levelLabel.setText(_translate("MainWindow", "Level:"))
        self.repeatLabel.setText(_translate("MainWindow", "Repetition:"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.analyzeButton.setText(_translate("MainWindow", "Analyze Collected Data"))